POST http://localhost:5051/Users
Content-Type: application/json

{
  "userName": "Anna",
  "password": "1234"
}

###
PUT http://localhost:5051/Users/2
Content-Type: application/json

{
  "userName": "AnnaUpdated",
  "password": "5678"
}

###
DELETE http://localhost:5051/Users/2

###
POST http://localhost:5051/Posts
Content-Type: application/json

{
  "title": "Test post",
  "body": "Hello Hello Hello",
  "userId": 2
}

###
PUT http://localhost:5051/Posts/2
Content-Type: application/json

{
  "title": "Updated post",
  "body": "Updated body",
  "userId": 2
}

###
DELETE http://localhost:5051/Posts/2

###
POST http://localhost:5051/Comments
Content-Type: application/json

{
  "body": "Nice post!",
  "userId": 2,
  "postId": 2
}

###
PUT http://localhost:5051/Comments/2
Content-Type: application/json

{
  "body": "Updated comment!",
  "userId": 2,
  "postId": 2
}

###
DELETE http://localhost:5051/Comments/2